# Generated by Django 5.2.5 on 2025-08-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='biling',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
