# Generated by Django 5.2.5 on 2025-08-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_biling'),
        ('games', '0005_remove_game_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='games',
            field=models.ManyToManyField(blank=True, null=True, related_name='games_company', to='games.game'),
        ),
    ]
