# Generated by Django 5.2.5 on 2025-08-19 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_games'),
        ('games', '0005_remove_game_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_of_company', to='company.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='games_company', to='games.game'),
        ),
    ]
