# Generated by Django 5.2.5 on 2025-08-22 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_purchase_company_alter_company_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='games',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
