# Generated by Django 4.2.11 on 2025-08-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='games/static/img'),
        ),
    ]
