# Generated by Django 5.2.5 on 2025-08-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='games/'),
        ),
    ]
