# Generated by Django 5.2.5 on 2025-08-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
