# Generated by Django 5.2.5 on 2025-08-16 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='online',
        ),
    ]
