# Generated by Django 5.2.5 on 2025-08-22 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_company_games_delete_purchase'),
        ('games', '0005_remove_game_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_of_game', to='company.company'),
        ),
    ]
