# Generated by Django 5.2.5 on 2025-08-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='user.svg', upload_to='user/'),
        ),
    ]
